// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package io.rsocket.rpc.extension.sample.proto;

public interface SimpleRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.netifi.rsocket.example.SimpleRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string requestMessage = 1;</code>
   * @return The requestMessage.
   */
  String getRequestMessage();
  /**
   * <code>string requestMessage = 1;</code>
   * @return The bytes for requestMessage.
   */
  com.google.protobuf.ByteString
      getRequestMessageBytes();
}
