// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package io.rsocket.rpc.extension.sample.proto;

public final class SimpleServiceProto {
  private SimpleServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_netifi_rsocket_example_SimpleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_netifi_rsocket_example_SimpleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_netifi_rsocket_example_SimpleResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_netifi_rsocket_example_SimpleResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rservice.proto\022\031io.netifi.rsocket.examp" +
      "le\032\033google/protobuf/empty.proto\"\'\n\rSimpl" +
      "eRequest\022\026\n\016requestMessage\030\001 \001(\t\")\n\016Simp" +
      "leResponse\022\027\n\017responseMessage\030\001 \001(\t2\252\004\n\r" +
      "SimpleService\022e\n\014RequestReply\022(.io.netif" +
      "i.rsocket.example.SimpleRequest\032).io.net" +
      "ifi.rsocket.example.SimpleResponse\"\000\022S\n\r" +
      "FireAndForget\022(.io.netifi.rsocket.exampl" +
      "e.SimpleRequest\032\026.google.protobuf.Empty\"" +
      "\000\022h\n\rRequestStream\022(.io.netifi.rsocket.e" +
      "xample.SimpleRequest\032).io.netifi.rsocket" +
      ".example.SimpleResponse\"\0000\001\022y\n\036Streaming" +
      "RequestSingleResponse\022(.io.netifi.rsocke" +
      "t.example.SimpleRequest\032).io.netifi.rsoc" +
      "ket.example.SimpleResponse\"\000(\001\022x\n\033Stream" +
      "ingRequestAndResponse\022(.io.netifi.rsocke" +
      "t.example.SimpleRequest\032).io.netifi.rsoc" +
      "ket.example.SimpleResponse\"\000(\0010\001B1\n\031io.n" +
      "etifi.rsocket.exampleB\022SimpleServiceProt" +
      "oP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_io_netifi_rsocket_example_SimpleRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_netifi_rsocket_example_SimpleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_netifi_rsocket_example_SimpleRequest_descriptor,
        new String[] { "RequestMessage", });
    internal_static_io_netifi_rsocket_example_SimpleResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_io_netifi_rsocket_example_SimpleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_netifi_rsocket_example_SimpleResponse_descriptor,
        new String[] { "ResponseMessage", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
