// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package io.rsocket.rpc.extension.sample.proto;

public interface SimpleResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.netifi.rsocket.example.SimpleResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string responseMessage = 1;</code>
   * @return The responseMessage.
   */
  String getResponseMessage();
  /**
   * <code>string responseMessage = 1;</code>
   * @return The bytes for responseMessage.
   */
  com.google.protobuf.ByteString
      getResponseMessageBytes();
}
